[versions]
# Android
androidGradlePlugin = "7.3.1"
compileTargetSdk = "33"
minSdk = "21"
versionCode = "1"

composeUi = "1.3.3"
composeFoundation = "1.3.1"
composeMaterial = "1.3.1"
composeActivity = "1.6.1"
composeCompiler = "1.4.0-alpha02"

lifecycleKtx = "2.5.1"

# iOS
deploymentTarget = "14.0"

#KMM
kotlin = "1.7.21"
version = "1.0"
kotlinxSerialization = "1.4.1"
kotlinxCoroutines = "1.6.4"

[libraries]
#Android
composeUi = { module = "androidx.compose.ui:ui" , version.ref = "composeUi"}
composeUiTooling = { module = "androidx.compose.ui:ui-tooling" , version.ref = "composeUi"}
composeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" , version.ref = "composeUi"}
composeFoundation = { module = "androidx.compose.foundation:foundation" , version.ref = "composeFoundation"}
composeMaterial = { module = "androidx.compose.material:material" , version.ref = "composeMaterial"}
composeActivity = { module = "androidx.activity:activity-compose" , version.ref = "composeActivity"}
viewModelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleKtx" }
liveDataKtx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleKtx" }

#KMM
kotlinxJsonSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization"}
kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }

[bundles]

[plugins]
